_wandb:
    value:
        cli_version: 0.22.3
        e:
            b477qyvvqe6l5td4b6gl07rvckmiyfpx:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "269294317568"
                        used: "127642890240"
                email: onetail0114@gmail.com
                executable: /mnt/data1/users/4xin/conda_envs/ML/bin/python
                git:
                    commit: e32bae14088e7d39050a18159a3dff7dd45e6d58
                    remote: https://github.com/bassammmm/uhh-ias-ml.git
                gpu: NVIDIA RTX A6000
                gpu_count: 5
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-8781349e-a5da-4a8f-d1dd-cae3c5c13860
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-2ee728c5-f032-225e-9f43-6ecc728d3cb8
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-250fe32c-24cc-81fe-b3d9-71264eafb3e8
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-daff8f6e-7edd-56b2-0c8e-daab0ecc81ae
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-28bc56a0-9ae8-a401-27d4-150180d85d6d
                host: ltgpu3
                memory:
                    total: "1082013392896"
                os: Linux-6.8.0-83-generic-x86_64-with-glibc2.39
                program: /ltstorage/home/4xin/uhh-ias-ml/train.py
                python: CPython 3.10.19
                root: /ltstorage/home/4xin/uhh-ias-ml
                startedAt: "2025-11-11T10:46:04.428829Z"
                writerId: b477qyvvqe6l5td4b6gl07rvckmiyfpx
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 1
                - 16
            "4": 3.10.19
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
architecture:
    value: decoder-only
batch_size:
    value: 32
d_ff:
    value: 1024
d_model:
    value: 256
device:
    value: cpu
dropout:
    value: 0.1
lr:
    value: 0.0003
max_seq_len:
    value: 256
n_heads:
    value: 8
n_layers:
    value: 4
num_epochs:
    value: 5
weight_decay:
    value: 0.01
